import { images } from "../design-system/assets/images"
import { RecipeCategories } from "../enums/recipeCategories"
import { RecipeProps } from "../types/recipe"

export const cookingRecipeData: RecipeProps[] = [
  {
    id: "1",
    name: "Bún bò",
    typeName: RecipeCategories.NOODLE,
    image: images.bunBo,
    description: "Bún và bò",
    cookingTime: "35",
    numberOfServing: "2",
    numberOfCalories: "600",
    levelOfDifficulty: "Dễ",
    ingredients: [
      { name: "Bún", quantity: "200g" },
      { name: "Bò", quantity: "150g" },
      { name: "Nước dùng", quantity: "500ml" },
      { name: "Rau sống", quantity: "100g" },
      { name: "Gia vị", quantity: "Theo khẩu vị" },
    ],
    instructions: [
      "Nấu nước dùng với xương bò và gia vị.",
      "Luộc bún trong nước sôi cho đến khi chín.",
      "Thái bò thành lát mỏng và trụng qua nước sôi.",
      "Cho bún vào tô, thêm nước dùng, thịt bò và rau sống.",
      "Rắc thêm gia vị và thưởng thức.",
    ],
    recipeVideoUrl: "https://www.youtube.com/watch?v=A_o2qfaTgKs&t=307s",
  },
  {
    id: "2",
    name: "Cơm sườn",
    typeName: RecipeCategories.NOODLE,
    image: images.comSuon,
    description: "Cơm và sườn",
    cookingTime: "45",
    numberOfServing: "3",
    numberOfCalories: "700",
    levelOfDifficulty: "Trung bình",
    ingredients: [
      { name: "Cơm", quantity: "300g" },
      { name: "Sườn heo", quantity: "250g" },
      { name: "Nước mắm", quantity: "2 muỗng canh" },
      { name: "Hành tây", quantity: "1 củ" },
      { name: "Gia vị", quantity: "Theo khẩu vị" },
    ],
    instructions: [
      "Nướng sườn heo với nước mắm và gia vị cho đến khi chín vàng.",
      "Nấu cơm trắng cho đến khi chín.",
      "Thái hành tây thành lát mỏng và xào sơ.",
      "Cho cơm ra đĩa, đặt sườn nướng lên trên và trang trí với hành tây.",
      "Thưởng thức cùng với nước mắm chấm.",
    ],
    recipeVideoUrl: "https://www.youtube.com/watch?v=WWX8mw4z6xQ",
  },
  {
    id: "3",
    name: "Hủ tiếu",
    typeName: RecipeCategories.NOODLE,
    image: images.huTieu,
    description: "Hủ và tiếu",
    cookingTime: "30",
    numberOfServing: "2",
    numberOfCalories: "500",
    levelOfDifficulty: "Dễ",
    ingredients: [
      { name: "Hủ tiếu", quantity: "200g" },
      { name: "Thịt heo", quantity: "150g" },
      { name: "Nước dùng", quantity: "500ml" },
      { name: "Rau sống", quantity: "100g" },
      { name: "Gia vị", quantity: "Theo khẩu vị" },
    ],
    instructions: [
      "Nấu nước dùng với xương heo và gia vị.",
      "Luộc hủ tiếu trong nước sôi cho đến khi chín.",
      "Thái thịt heo thành lát mỏng và trụng qua nước sôi.",
      "Cho hủ tiếu vào tô, thêm nước dùng, thịt heo và rau sống.",
      "Rắc thêm gia vị và thưởng thức.",
    ],
    recipeVideoUrl: "https://www.youtube.com/watch?v=fziqSn-xkws",
  },
  {
    id: "4",
    name: "Phở bò",
    typeName: RecipeCategories.NOODLE,
    image: images.phoBo,
    description: "Phở và bò",
    cookingTime: "60",
    numberOfServing: "4",
    numberOfCalories: "800",
    levelOfDifficulty: "Khó",
    ingredients: [
      { name: "Phở", quantity: "300g" },
      { name: "Bò", quantity: "200g" },
      { name: "Nước dùng", quantity: "1L" },
      { name: "Hành lá", quantity: "2 cây" },
      { name: "Gia vị", quantity: "Theo khẩu vị" },
    ],
    instructions: [
      "Nấu nước dùng với xương bò và gia vị trong 1 giờ.",
      "Luộc phở trong nước sôi cho đến khi chín.",
      "Thái bò thành lát mỏng và trụng qua nước sôi.",
      "Cho phở vào tô, thêm nước dùng, thịt bò và hành lá.",
      "Rắc thêm gia vị và thưởng thức.",
    ],
    recipeVideoUrl: "https://www.youtube.com/watch?v=c9GfHgMk1ac",
  },
]
