import { images } from "../design-system/assets/images"
import { LevelOfDifficulties } from "../enums"
import { RecipeCategories } from "../enums/recipeCategories"
import { RecipeProps } from "../types/recipe"

export const cookingRecipeData: RecipeProps[] = [
  {
    id: "1",
    name: "Bún bò",
    typeName: RecipeCategories.NOODLE,
    image: images.bunBo,
    description: "Bún và bò",
    cookingTime: "35",
    numberOfServing: "2",
    numberOfCalories: "600",
    levelOfDifficulty: LevelOfDifficulties.EASY,
    ingredients: [
      { name: "Bún", quantity: "200g" },
      { name: "Bò", quantity: "150g" },
      { name: "Nước dùng", quantity: "500ml" },
      { name: "Rau sống", quantity: "100g" },
      { name: "Gia vị", quantity: "Theo khẩu vị" },
    ],
    instructions: [
      "Nấu nước dùng với xương bò và gia vị.",
      "Luộc bún trong nước sôi cho đến khi chín.",
      "Thái bò thành lát mỏng và trụng qua nước sôi.",
      "Cho bún vào tô, thêm nước dùng, thịt bò và rau sống.",
      "Rắc thêm gia vị và thưởng thức.",
    ],
    recipeVideoUrl: "https://www.youtube.com/watch?v=A_o2qfaTgKs&t=307s",
  },
  {
    id: "2",
    name: "Cơm sườn",
    typeName: RecipeCategories.RICE,
    image: images.comSuon,
    description: "Cơm và sườn",
    cookingTime: "45",
    numberOfServing: "3",
    numberOfCalories: "700",
    levelOfDifficulty: LevelOfDifficulties.MEDIUM,
    ingredients: [
      { name: "Cơm", quantity: "300g" },
      { name: "Sườn heo", quantity: "250g" },
      { name: "Nước mắm", quantity: "2 muỗng canh" },
      { name: "Hành tây", quantity: "1 củ" },
      { name: "Gia vị", quantity: "Theo khẩu vị" },
    ],
    instructions: [
      "Nướng sườn heo với nước mắm và gia vị cho đến khi chín vàng.",
      "Nấu cơm trắng cho đến khi chín.",
      "Thái hành tây thành lát mỏng và xào sơ.",
      "Cho cơm ra đĩa, đặt sườn nướng lên trên và trang trí với hành tây.",
      "Thưởng thức cùng với nước mắm chấm.",
    ],
    recipeVideoUrl: "https://www.youtube.com/watch?v=WWX8mw4z6xQ",
  },
  {
    id: "3",
    name: "Hủ tiếu",
    typeName: RecipeCategories.NOODLE,
    image: images.huTieu,
    description: "Hủ và tiếu",
    cookingTime: "30",
    numberOfServing: "2",
    numberOfCalories: "500",
    levelOfDifficulty: LevelOfDifficulties.EASY,
    ingredients: [
      { name: "Hủ tiếu", quantity: "200g" },
      { name: "Thịt heo", quantity: "150g" },
      { name: "Nước dùng", quantity: "500ml" },
      { name: "Rau sống", quantity: "100g" },
      { name: "Gia vị", quantity: "Theo khẩu vị" },
    ],
    instructions: [
      "Nấu nước dùng với xương heo và gia vị.",
      "Luộc hủ tiếu trong nước sôi cho đến khi chín.",
      "Thái thịt heo thành lát mỏng và trụng qua nước sôi.",
      "Cho hủ tiếu vào tô, thêm nước dùng, thịt heo và rau sống.",
      "Rắc thêm gia vị và thưởng thức.",
    ],
    recipeVideoUrl: "https://www.youtube.com/watch?v=fziqSn-xkws",
  },
  {
    id: "4",
    name: "Phở bò",
    typeName: RecipeCategories.NOODLE,
    image: images.phoBo,
    description: "Phở và bò",
    cookingTime: "60",
    numberOfServing: "4",
    numberOfCalories: "800",
    levelOfDifficulty: LevelOfDifficulties.HARD,
    ingredients: [
      { name: "Phở", quantity: "300g" },
      { name: "Bò", quantity: "200g" },
      { name: "Nước dùng", quantity: "1L" },
      { name: "Hành lá", quantity: "2 cây" },
      { name: "Gia vị", quantity: "Theo khẩu vị" },
    ],
    instructions: [
      "Nấu nước dùng với xương bò và gia vị trong 1 giờ.",
      "Luộc phở trong nước sôi cho đến khi chín.",
      "Thái bò thành lát mỏng và trụng qua nước sôi.",
      "Cho phở vào tô, thêm nước dùng, thịt bò và hành lá.",
      "Rắc thêm gia vị và thưởng thức.",
    ],
    recipeVideoUrl: "https://www.youtube.com/watch?v=c9GfHgMk1ac",
  },
  {
    id: "5",
    name: "Mì Quảng",
    typeName: RecipeCategories.NOODLE,
    image: images.miQuang,
    description: "Mì và Quảng",
    cookingTime: "50",
    numberOfServing: "3",
    numberOfCalories: "650",
    levelOfDifficulty: LevelOfDifficulties.MEDIUM,
    ingredients: [
      { name: "Mì Quảng", quantity: "250g" },
      { name: "Tôm", quantity: "150g" },
      { name: "Thịt gà", quantity: "200g" },
      { name: "Nước dùng", quantity: "600ml" },
      { name: "Rau sống", quantity: "100g" },
      { name: "Gia vị", quantity: "Theo khẩu vị" },
    ],
    instructions: [
      "Nấu nước dùng với xương gà và gia vị.",
      "Luộc mì Quảng trong nước sôi cho đến khi chín.",
      "Thái thịt gà và tôm thành lát mỏng.",
      "Cho mì Quảng vào tô, thêm nước dùng, thịt gà, tôm và rau sống.",
      "Rắc thêm gia vị và thưởng thức.",
    ],
    recipeVideoUrl: "https://www.youtube.com/watch?v=mRYABUuK6RE",
  },
  {
    id: "6",
    name: "Cơm gà",
    typeName: RecipeCategories.RICE,
    image: images.comGa,
    description: "Cơm và gà",
    cookingTime: "40",
    numberOfServing: "2",
    numberOfCalories: "550",
    levelOfDifficulty: LevelOfDifficulties.EASY,
    ingredients: [
      { name: "Cơm", quantity: "200g" },
      { name: "Gà", quantity: "200g" },
      { name: "Nước dùng", quantity: "500ml" },
      { name: "Rau sống", quantity: "100g" },
      { name: "Gia vị", quantity: "Theo khẩu vị" },
    ],
    instructions: [
      "Nấu nước dùng với xương gà và gia vị.",
      "Luộc cơm trong nước sôi cho đến khi chín.",
      "Thái gà thành lát mỏng và trụng qua nước sôi.",
      "Cho cơm vào tô, thêm nước dùng, thịt gà và rau sống.",
      "Rắc thêm gia vị và thưởng thức.",
    ],
    recipeVideoUrl: "https://www.youtube.com/watch?v=zDxW95100Hg",
  },
  {
    id: "7",
    name: "Cơm chiên dương châu",
    typeName: RecipeCategories.RICE,
    image: images.comChienDuongChau,
    description: "Cơm và chiên dương châu",
    cookingTime: "40",
    numberOfServing: "2",
    numberOfCalories: "550",
    levelOfDifficulty: LevelOfDifficulties.EASY,
    ingredients: [
      { name: "Cơm", quantity: "200g" },
      { name: "Tôm", quantity: "100g" },
      { name: "Trứng", quantity: "2 quả" },
      { name: "Hành tây", quantity: "1 củ" },
      { name: "Gia vị", quantity: "Theo khẩu vị" },
    ],
    instructions: [
      "Chiên hành tây trong chảo cho đến khi vàng.",
      "Thêm tôm vào chiên cho đến khi chín.",
      "Đập trứng vào chảo, khuấy đều cho đến khi trứng chín.",
      "Thêm cơm vào chảo, xào đều với gia vị.",
      "Trang trí với rau sống và thưởng thức.",
    ],
    recipeVideoUrl: "https://www.youtube.com/watch?v=_cdBAMq5KZ0",
  },
  {
    id: "8",
    name: "Cơm trộn Hàn Quốc",
    typeName: RecipeCategories.RICE,
    image: images.comTronHanQuoc,
    description: "Cơm và trộn Hàn Quốc",
    cookingTime: "30",
    numberOfServing: "2",
    numberOfCalories: "600",
    levelOfDifficulty: LevelOfDifficulties.EASY,
    ingredients: [
      { name: "Cơm", quantity: "200g" },
      { name: "Rau củ", quantity: "150g" },
      { name: "Thịt bò", quantity: "100g" },
      { name: "Trứng", quantity: "1 quả" },
      { name: "Gia vị", quantity: "Theo khẩu vị" },
    ],
    instructions: [
      "Nấu cơm trắng cho đến khi chín.",
      "Thái rau củ và thịt bò thành lát mỏng.",
      "Chiên trứng cho đến khi lòng đỏ còn nguyên.",
      "Cho cơm vào tô, xếp rau củ, thịt bò và trứng lên trên.",
      "Rắc thêm gia vị và trộn đều trước khi thưởng thức.",
    ],
    recipeVideoUrl: "https://www.youtube.com/watch?v=Z0iAvgVQk9E",
  },
]
