/* eslint-disable @typescript-eslint/no-require-imports */
export const images = {
  appLogo: require("./app-logo.png"),
  bunBo: require("./bun-bo.webp"),
  comChienDuongChau: require("./com-chien-duong-chau.webp"),
  comGa: require("./com-ga.webp"),
  comSuon: require("./com-suon.webp"),
  comTronHanQuoc: require("./com-tron-han-quoc.webp"),
  dad: require("./dad.webp"),
  enFlag: require("./en-flag.webp"),
  huTieu: require("./hu-tieu.webp"),
  me: require("./me.webp"),
  miQuang: require("./mi-quang.webp"),
  mom: require("./mom.webp"),
  noodle: require("./noodle.webp"),
  phoBo: require("./pho-bo.webp"),
  restaurant: require("./restaurant.webp"),
  rice: require("./rice.webp"),
  sister: require("./sister.webp"),
  starterMeal: require("./starter.webp"),
  viFlag: require("./vi-flag.webp"),
  welcome: require("./welcome.webp"),
}
