name: CI

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: write # Cho phép bot push thay đổi

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Expo Doctor
        run: npx expo-doctor

      - name: Run auto-fix (ESLint + Prettier)
        run: |
          yarn lint:fix
          yarn format

      - name: Check ESLint
        run: yarn lint

      - name: Check formatting
        run: yarn format:check

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: auto-fix lint/prettier"
            git push origin HEAD:${GITHUB_HEAD_REF}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
